version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: model_mpg
    ports:
      - "8000:8000"
    command:
      - "runserver"
      - "0.0.0.0:8000"